version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_scraper_backend
    command: uvicorn agentic_scraper.backend.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app/src
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic_scraper_frontend
    command: streamlit run src/agentic_scraper/frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app/src
    restart: unless-stopped
