FROM python:3.11-slim-bullseye

WORKDIR /app
ENV PYTHONPATH=/app/src

# System dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    build-essential curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml README.md ./
COPY src ./src

RUN pip install --no-cache-dir ".[dev]"


EXPOSE 8501

CMD ["streamlit", "run", "src/agentic_scraper/frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
