services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agentic_scraper_backend
    command: uvicorn agentic_scraper.backend.api.main:app --host 0.0.0.0 --port 10000
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - .:/app  # ⚠️ Dev only — remove for prod
    environment:
      PYTHONPATH: /app/src
    restart: unless-stopped
    networks:
      - agentic_scraper_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: agentic_scraper_frontend
    command: streamlit run src/agentic_scraper/frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app  # ⚠️ Dev only — remove for prod
    environment:
      PYTHONPATH: /app/src
    restart: unless-stopped
    networks:
      - agentic_scraper_network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  agentic_scraper_network:
    driver: bridge
